CREATE TABLE "APP"."PP_CLIENT"
(
   ID bigint PRIMARY KEY NOT NULL,
   ADRESSE varchar(255),
   EMAIL varchar(255),
   FAX varchar(255),
   NOM varchar(255),
   PORTABLE varchar(255),
   PORTABLE2 varchar(255),
   RAISONSOCIALE varchar(255),
   TEL varchar(255),
   VILLE varchar(255)
)
;
CREATE UNIQUE INDEX SQL140930172424570 ON "APP"."PP_CLIENT"(ID)
;
CREATE TABLE "APP"."BOOK"
(
   ID bigint PRIMARY KEY NOT NULL,
   DATEINS date,
   DESCRIPTION varchar(2000),
   ILLUSTRATIONS smallint DEFAULT 0,
   ISBN varchar(255),
   NBOFPAGE int,
   PRICE decimal(10),
   TITLE varchar(255) NOT NULL
)
;
CREATE UNIQUE INDEX SQL140918234633200 ON "APP"."BOOK"(ID)
;
CREATE TABLE "APP"."P_AUTORISATION"
(
   ID bigint PRIMARY KEY NOT NULL,
   DATEAUTORISATION date,
   NUMERO varchar(255),
   CLIENT_FK bigint
)
;
ALTER TABLE "APP"."P_AUTORISATION"
ADD CONSTRAINT PTORISATIONCLENTFK
FOREIGN KEY (CLIENT_FK)
REFERENCES "APP"."PP_CLIENT"(ID)
;
CREATE INDEX SQL140930172426050 ON "APP"."P_AUTORISATION"(CLIENT_FK)
;
CREATE UNIQUE INDEX SQL140930172424950 ON "APP"."P_AUTORISATION"(ID)
;
CREATE TABLE "APP"."P_AUTORISATION_ESPECE"
(
   AUTORISATION_FK bigint NOT NULL,
   ESPECE_FK bigint NOT NULL,
   CONSTRAINT SQL140930172425860 PRIMARY KEY (AUTORISATION_FK,ESPECE_FK)
)
;
ALTER TABLE "APP"."P_AUTORISATION_ESPECE"
ADD CONSTRAINT PTRSTONESPECESPCFK
FOREIGN KEY (ESPECE_FK)
REFERENCES "APP"."P_ESPECE"(ID)
;
ALTER TABLE "APP"."P_AUTORISATION_ESPECE"
ADD CONSTRAINT PTRSTNSPECETRSTNFK
FOREIGN KEY (AUTORISATION_FK)
REFERENCES "APP"."P_AUTORISATION"(ID)
;
CREATE INDEX SQL140930172426970 ON "APP"."P_AUTORISATION_ESPECE"(ESPECE_FK)
;
CREATE INDEX SQL140930172427100 ON "APP"."P_AUTORISATION_ESPECE"(AUTORISATION_FK)
;
CREATE UNIQUE INDEX SQL140930172425860 ON "APP"."P_AUTORISATION_ESPECE"
(
  AUTORISATION_FK,
  ESPECE_FK
)
;
CREATE TABLE "APP"."P_CLIENT_TYPE_CLIENT"
(
   CLIENT_FK bigint NOT NULL,
   TYPE_CLIENT_FK bigint NOT NULL,
   CONSTRAINT SQL140930172425670 PRIMARY KEY (CLIENT_FK,TYPE_CLIENT_FK)
)
;
ALTER TABLE "APP"."P_CLIENT_TYPE_CLIENT"
ADD CONSTRAINT PCLNTTYPCTYPCLNTFK
FOREIGN KEY (TYPE_CLIENT_FK)
REFERENCES "APP"."P_TYPE_CLIENT"(ID)
;
ALTER TABLE "APP"."P_CLIENT_TYPE_CLIENT"
ADD CONSTRAINT PCLNTTYPCLNTCLNTFK
FOREIGN KEY (CLIENT_FK)
REFERENCES "APP"."PP_CLIENT"(ID)
;
CREATE INDEX SQL140930172426840 ON "APP"."P_CLIENT_TYPE_CLIENT"(CLIENT_FK)
;
CREATE INDEX SQL140930172426720 ON "APP"."P_CLIENT_TYPE_CLIENT"(TYPE_CLIENT_FK)
;
CREATE UNIQUE INDEX SQL140930172425670 ON "APP"."P_CLIENT_TYPE_CLIENT"
(
  CLIENT_FK,
  TYPE_CLIENT_FK
)
;
CREATE TABLE "APP"."P_ESPECE"
(
   ID bigint PRIMARY KEY NOT NULL,
   NOM varchar(255)
)
;
CREATE UNIQUE INDEX SQL140930172425130 ON "APP"."P_ESPECE"(ID)
;
CREATE TABLE "APP"."P_PECHE"
(
   ID bigint PRIMARY KEY NOT NULL,
   DATE_PECHE date,
   ESPECE_FK bigint,
   CLIENT_FK bigint
)
;
ALTER TABLE "APP"."P_PECHE"
ADD CONSTRAINT P_PECHE_CLIENT_FK
FOREIGN KEY (CLIENT_FK)
REFERENCES "APP"."PP_CLIENT"(ID)
;
ALTER TABLE "APP"."P_PECHE"
ADD CONSTRAINT P_PECHE_ESPECE_FK
FOREIGN KEY (ESPECE_FK)
REFERENCES "APP"."P_ESPECE"(ID)
;
CREATE INDEX SQL140930172426200 ON "APP"."P_PECHE"(CLIENT_FK)
;
CREATE UNIQUE INDEX SQL140930172425310 ON "APP"."P_PECHE"(ID)
;
CREATE INDEX SQL140930172426340 ON "APP"."P_PECHE"(ESPECE_FK)
;
CREATE TABLE "APP"."P_TYPE_CLIENT"
(
   ID bigint PRIMARY KEY NOT NULL,
   TYPE_CLIENT varchar(255)
)
;
CREATE UNIQUE INDEX SQL140930172424770 ON "APP"."P_TYPE_CLIENT"(ID)
;
CREATE TABLE "APP"."PP_CLIENT"
(
   ID bigint PRIMARY KEY NOT NULL,
   ADRESSE varchar(255),
   EMAIL varchar(255),
   FAX varchar(255),
   NOM varchar(255),
   PORTABLE varchar(255),
   PORTABLE2 varchar(255),
   RAISONSOCIALE varchar(255),
   TEL varchar(255),
   VILLE varchar(255)
)
;
CREATE UNIQUE INDEX SQL140930172424570 ON "APP"."PP_CLIENT"(ID)
;
CREATE TABLE "APP"."SEQUENCE"
(
   SEQ_NAME varchar(50) PRIMARY KEY NOT NULL,
   SEQ_COUNT decimal(15)
)
;
CREATE UNIQUE INDEX SQL140927144340570 ON "APP"."SEQUENCE"(SEQ_NAME)
;
CREATE TABLE "APP"."T_AUTHOR"
(
   ID bigint PRIMARY KEY NOT NULL,
   CITY varchar(50) NOT NULL,
   FIRSTNAME varchar(50) NOT NULL,
   LASTNAME varchar(50) NOT NULL
)
;


